Repository AY2425S2-CS2103-F09-4/tp, pull requests merged in 2025-03, with the labels that each got.

#19 Update AboutUs for Ming Shan
  docs/AboutUs.md
  docs/team/mingshan2705.md
Labels: type.Task

#32 Update Developer Guide - Use cases
  docs/DeveloperGuide.md
Labels: type.Task

#33 Update Developer Guide - Non-functional Requirements
  docs/DeveloperGuide.md
Labels: type.Story, type.Task

#36 Update DG
  docs/DeveloperGuide.md
Labels: type.Task

#49 Fix trailing whitespace issue present in CI
  README.md
  docs/DeveloperGuide.md
Labels: priority.High

#47 Add name prefix functionality for Find Command
  .gitignore
  docs/DeveloperGuide.md
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
Labels: priority.High

#53 Add task description
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/TaskCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/TaskCommandParser.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/task/Task.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/storage/JsonAdaptedTask.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
Labels: priority.High

#65 Add tag prefix functionality for Find Command
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/model/person/TagsInKeywordsPredicate.java
  src/main/java/seedu/address/model/tag/Tag.java
Labels: priority.High

#68 Update User Guide and Help Command
  docs/UserGuide.md
  docs/images/findAlexBerniceResult.png
  docs/images/findColleaguesFriendsResult.png
  src/main/java/seedu/address/ui/HelpWindow.java
Labels: priority.High

#63 Feature task status report
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/CommandResult.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/ReportCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/ReportCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/resources/view/MainWindow.fxml
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
Labels: priority.High

#75 Resolve merge conflicts across all files and fix checkstyle errors
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/TaskStatusCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
Labels: priority.High

#81 feat(report): update report command to reflect task status
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/ReportCommand.java
  src/main/java/seedu/address/logic/commands/SetDueDateCommand.java
  src/main/java/seedu/address/logic/commands/TaskCommand.java
  src/main/java/seedu/address/logic/commands/TaskStatusCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
Labels: priority.High

#91 update image to better illustrate report command
  docs/images/report.png
Labels: type.Task

#92 update information for image retrieval
  docs/UserGuide.md
Labels: type.Task

#95 Add functionality to find members by task description priority
  docs/UserGuide.md
  docs/images/findBbqResult.png
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/model/person/TasksInKeywordsPredicate.java
Labels: priority.High

#106 Update UML diagram for LogicClass
  docs/diagrams/LogicClassDiagram.puml
Labels: priority.High

#114 update status names for feature compliance
  src/main/java/seedu/address/model/util/SampleDataUtil.java
Labels: type.Task

#119 Update User Guide to reflect latest find command
  docs/UserGuide.md
  docs/images/findInternBbqResult.jpg
  docs/images/findbbqResult.png
Labels: priority.High

#116 Update UML diagram for ModelClass
  docs/diagrams/ModelClassDiagram.puml
Labels: type.Task
