Repository AY2425S2-CS2103-F09-4/tp, pull requests merged in 2025-04, with the labels that each got.

#137 make command word case-insensitive
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
Labels: type.Enhancement

#141 Add test cases for delete task feature
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/DeleteTaskCommand.java
  src/main/java/seedu/address/logic/commands/SetDueDateCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/DeleteTaskCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/task/Task.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DeleteTaskCommandTest.java
  src/test/java/seedu/address/logic/commands/SetDueDateCommandTest.java
  src/test/java/seedu/address/logic/parser/DeleteTaskCommandParserTest.java
Labels: alpha-bug

#143 Add and edit commands
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/Ui.png
  docs/images/addBestyCroweInput.png
  docs/images/addBestyCroweResult.png
  docs/images/editBestyCroweInput.png
  docs/images/editBestyCroweResult.png
  docs/images/findAlexBerniceResult.png
  docs/images/findAlexDavidResult.png
  docs/images/findBbqResult.png
  docs/images/findColleaguesFriendsResult.png
  docs/images/findInternBBQResult.png
  docs/images/findInternBbqResult.jpg
  docs/images/findbbqResult.png
  docs/images/helpMessage.png
  docs/images/listtasksAlex1.png
  docs/images/listtasksAlex2.png
  docs/images/listtasksBetsy.png
  docs/images/listtasksJohn1.png
  docs/images/listtasksJohn2.png
  docs/images/listtasksJungkook.png
  docs/images/markTaskResult.png
  docs/images/report.png
  docs/images/reportResult.png
  docs/images/setduedate.png
  docs/images/taskBerniceTaskDescOnly.png
  docs/images/taskBetsyFullCommand.png
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/java/seedu/address/ui/ResultDisplay.java
  src/main/resources/images/TeamScape_icon.png
  src/main/resources/images/TeamScape_icon_32.png
  src/main/resources/images/TeamScape_icon_original.png
  src/main/resources/images/background.png
  src/main/resources/images/images.jpg
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/Extensions.css
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/PersonListCard.fxml
  src/main/resources/view/PersonListPanel.fxml
  src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java
  src/test/java/seedu/address/logic/parser/TaskCommandParserTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
Labels: type.Enhancement, type.Bug, severity.High, alpha-bug

#147 Fix error message to show actual task index that is invalid
  src/main/java/seedu/address/logic/commands/TaskStatusCommand.java
Labels: alpha-bug

#148 Update mark help command
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/TaskStatusCommand.java
Labels: alpha-bug

#150 display users with their assigned tasks by status
  src/main/java/seedu/address/logic/commands/CommandResult.java
  src/main/java/seedu/address/logic/commands/ReportCommand.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/ReportPanel.java
Labels: type.Enhancement

#153 update images for user guide
  docs/images/report1.png
  docs/images/report2.png
  docs/images/report3.png
Labels: type.Task

#154 update user guide for report command
  docs/UserGuide.md
Labels: type.Task

#156 improve formatting in user guide
  docs/UserGuide.md
Labels: type.Enhancement

#163 Update user guide
  docs/UserGuide.md
  docs/images/Ui.png
  docs/images/addBestyCroweInput.png
  docs/images/addBestyCroweResult.png
  docs/images/findAlexBerniceResult.png
  docs/images/findColleaguesFriendResult.png
  docs/images/findbbqResult.png
  docs/images/listtasksAlex.png
  docs/images/listtasksBetsy.png
  docs/images/markTaskResult.png
  docs/images/setduedate.png
  docs/images/taskBerniceTaskDescOnly.png
  docs/images/taskBetsyFullCommand.png
Labels: priority.High

#165 Fix standardisation of mark status
  src/main/java/seedu/address/logic/parser/TaskStatusCommandParser.java
Labels: alpha-bug

#170 Update UG and DG
  docs/AboutUs.md
  docs/Configuration.md
  docs/DevOps.md
  docs/DeveloperGuide.md
  docs/Documentation.md
  docs/Logging.md
  docs/SettingUp.md
  docs/Testing.md
  docs/UserGuide.md
  docs/diagrams/LogicClassDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/ParserClasses.puml
  docs/diagrams/StorageClassDiagram.puml
  docs/diagrams/TaskCommandSequenceDiagram.puml
  docs/diagrams/TaskModelClassDiagram.puml
  docs/diagrams/UiClassDiagram.puml
  docs/diagrams/add-remark/ParserClass.puml
  docs/images/deltaskInput.png
  docs/images/deltaskOutput.png
  docs/images/editBestyCroweInput.png
  docs/images/editBestyCroweResult.png
  docs/images/findColleaguesFriendsResult.png
  docs/images/findInternBBQResult.png
  docs/images/listtasksJohn1.png
  docs/images/listtasksJohn2.png
  docs/images/report.png
  docs/index.md
Labels: type.Task

#172 reorder task status for consistency
  src/main/java/seedu/address/ui/MainWindow.java
Labels: type.Enhancement

#182 standardize hyphenation for task status
  docs/UserGuide.md
Labels: alpha-bug

#196 update user guide for report command
  docs/UserGuide.md
Labels: type.Enhancement

#198 Update Developer Guide with task report details
  docs/DeveloperGuide.md
Labels: type.Task

#298 remove unnecessary ReportCommandParser and simplify logic
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/ReportCommandParser.java
Labels: type.Enhancement

#300 change task status label
  src/main/java/seedu/address/model/util/SampleDataUtil.java
Labels: type.Enhancement

#302 change default task status label
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
Labels: type.Enhancement

#308 display no task found message when no tasks exist for report command
  src/main/java/seedu/address/logic/commands/ReportCommand.java
Labels: type.Enhancement

#310 standardize naming conventions and update implemention details for developer guide
  docs/DeveloperGuide.md
Labels: type.Task

#306 Resolve PED bugs
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/ModelClassDiagram.puml
  docs/images/addBestyCroweInput.png
  docs/images/addBestyCroweResult.png
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/other/Other.java
  src/main/java/seedu/address/model/person/Phone.java
  src/main/java/seedu/address/model/skill/Skill.java
  src/main/java/seedu/address/model/tag/Tag.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedOther.java
  src/main/java/seedu/address/storage/JsonAdaptedSkill.java
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/person/NameContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/person/PhoneTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: type.Bug

#312 update UML diagrams for report command
  docs/diagrams/LogicClassDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/ReportCommandSequenceDiagram.puml
Labels: type.Task

#319 Limit Find Command prefixes to 1 type only and 1 instance
  docs/UserGuide.md
  docs/index.md
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
Labels: priority.High

#325 update testcases for report command
  src/test/java/seedu/address/logic/commands/ReportCommandTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
Labels: type.Enhancement
